#!/bin/bash

webcam_url="https:/{octopi-IP}/webcam/?action=stream"
twitch="rtmp://live.twitch.tv/app/{ID}"

docker run -d --name twitch jrottenberg/ffmpeg -d -re -i $webcam_url -pix_fmt yuvj420p -x264-params keyint=48:min-keyint=48:scenecut=-1 -s 1920x1080 -b:v 4500k -b:a 128k -ar 44100 -acodec aac -vcodec libx264 -preset ultrafast -crf 28 -threads 6 -f flv $twitch
